services:
  - type: web
    name: render-chatbot-local
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
    healthCheckPath: /health