services:
  - type: web
    name: shorties-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python shorties_server.py
    envVars:
      - key: PORT
        value: 10000